import { load } from 'cheerio';
import { checkedId, sourceText } from '../shared/sourceHttp.js';
import { ProviderGatewayError, type ContentProviderAdapter } from '../types.js';
const origin='https://novelping.com', providerId='novelping';
const id=(value:string)=>checkedId(value,/^[a-z0-9][a-z0-9-]{0,220}$/);
function bookId(href:string|undefined){if(!href)return undefined;const u=new URL(href,origin);return u.origin===origin?u.pathname.match(/^\/book\/([a-z0-9-]+)$/)?.[1]:undefined;}
export const novelPingAdapter:ContentProviderAdapter={
 definition:{id:providerId,name:'NovelPing',mediaTypes:['novel'],capabilities:['search','details','chapters','textContent'],status:'limited',statusNote:'Public English adapter; Render and physical reader verification pending.',enabledByDefault:true},
 async search(query){const $=load(await sourceText(origin,'/search?keyword='+encodeURIComponent(query)));return $('.novel-title a').toArray().flatMap(el=>{const a=$(el),sourceId=bookId(a.attr('href'));if(!sourceId)return [];const cover=a.closest('.row').find('img').first().attr('src');return [{id:sourceId,providerId,sourceId,mediaType:'novel' as const,title:a.text().trim(),coverUrl:cover?new URL(cover,origin).href:undefined}]}).slice(0,20);},
 async getDetails(sourceId){const $=load(await sourceText(origin,'/book/'+id(sourceId)));const title=$('h1').first().text().trim();if(!title)throw new ProviderGatewayError('NovelPing title unavailable.',502);return {providerId,sourceId,mediaType:'novel',title,coverUrl:$('meta[property="og:image"]').attr('content'),description:$('.desc-text').text().trim(),genres:[],language:'en'};},
 async getChapters(sourceId){const slug=id(sourceId),$=load(await sourceText(origin,'/ajax/chapter-archive?novelId='+slug));const seen=new Set<string>();const chapters=$('a[href]').toArray().flatMap(el=>{const a=$(el),u=new URL(a.attr('href')||'/',origin);const match=u.pathname.match(/^\/book\/([a-z0-9-]+)\/([a-z0-9-]+)$/);if(u.origin!==origin||!match||match[1]!==slug||seen.has(match[2]))return [];seen.add(match[2]);const title=a.text().trim(),number=Number(title.match(/(?:Chapter|Ch\.)[\s:'-]*(\d+(?:\.\d+)?)/i)?.[1] ?? match[2].match(/^chapter-(\d+(?:\.\d+)?)/)?.[1]);if(!Number.isFinite(number))return [];return [{id:match[2],providerId,mediaId:slug,chapterNumber:number,title,language:'en'}]});if(!chapters.length)throw new ProviderGatewayError('NovelPing chapter list unavailable.',502);return chapters.sort((a,b)=>a.chapterNumber-b.chapterNumber);},
 async getNovelContent(sourceId,chapterId){id(sourceId);id(chapterId);const chapters=await novelPingAdapter.getChapters!(sourceId);if(!chapters.some(ch=>ch.id===chapterId))throw new ProviderGatewayError('Chapter is not listed for this novel.',404);const $=load(await sourceText(origin,'/book/'+sourceId+'/'+chapterId));$('#chr-content script,#chr-content style,#chr-content .ads').remove();const paragraphs=$('#chr-content p').toArray().map(el=>$(el).text().trim()).filter(Boolean);if(!paragraphs.length)throw new ProviderGatewayError('Public NovelPing text unavailable.',502);const index=chapters.findIndex(ch=>ch.id===chapterId);return {providerId,mediaId:sourceId,chapterId,title:$('h2').first().text().trim(),paragraphs,language:'en',previousChapterId:chapters[index-1]?.id,nextChapterId:chapters[index+1]?.id};}
};
