warning: in the working copy of 'PHASE-6.5-PROVIDER-MATRIX.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app.config.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(tabs)/downloads.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(tabs)/index.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(tabs)/library.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(tabs)/search.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(tabs)/settings.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/_layout.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/anime/[id]/index.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/anime/[id]/watch/[episodeId].tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/anime/_layout.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/manga/[id]/index.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/manga/[id]/read/[chapterId].tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/manga/_layout.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/novel/[id]/index.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/novel/[id]/read/[chapterId].tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/novel/_layout.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/sources.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'backend/.env.example', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'backend/README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'backend/package.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'backend/src/app.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'backend/src/config/env.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'backend/src/controllers/content.controller.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'backend/src/controllers/favorites.controller.ts', LF will be replaced by CRLF the next time Git touches it
